name = "walcdn-db"
compatibility_date = "2024-12-05"

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "00000000-0000-0000-0000-000000000000"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "00000000-0000-0000-0000-000000000001"

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "walcdn-mainnet-db"
database_id = "68aebed4-3cd4-428f-a0f7-5c67721f9e90"
