name = "walcdn-retriever"
main = "bin/retriever.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "00000000-0000-0000-0000-000000000000"

[env.dev.vars]
ENVIRONMENT = "dev"
CACHE_TTL = 86400
DNS_ROOT = ".localhost"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "dev-db"
database_id = "00000000-0000-0000-0000-000000000001"

[[env.mainnet.routes]]
pattern = "*.walcdn.io/*"
zone_name = "walcdn.io"

[env.mainnet.vars]
ENVIRONMENT = "mainnet "
CACHE_TTL = 86400
DNS_ROOT = ".walcdn.io"

[[env.mainnet.d1_databases]]
binding = "DB"
database_name = "walcdn-mainnet-db"
database_id = "68aebed4-3cd4-428f-a0f7-5c67721f9e90"
